meta_product_name: "ValueJunk"
meta_title: "ValueJunk - Don't throw them, reuse them !"
meta_description: "ValueJunk is not just another marketplace. We want to make upcycling,fun, trendy, and collaborative."
meta_image: "banner-og-full-content.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
